### ISSUE TITLE
Panel Autohide while attempting to select contents

### ISSUE THREAD

**Issue by ajaxStardust** [sirmspencer/vscode-autohide#27] opened 2022-12-29 01:17 UTC
The panel closes while attempting to select text therein. I like that it will autohide. I don't want it to autohide while i'm working in that area. 
:)

E.g. Terminal > Output > Git

**Comment by artginzburg** [comment] 2022-12-30 07:44
Duplicate of #19

**Comment by ajaxStardust** [comment] 2022-12-30 07:46
No. Clicking in the panel does not hide it.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Voice/ Text:  +1 (814) 325-7573
my.indeed.com/p/9n1d3mc <https://my.indeed.com/p/9n1d3mc/preview>

linkedin.com/in/jeffreysabarese 
<https://www.linkedin.com/in/jeffreysabarese>
@ajaxStardust

www.CentreWebDesign.com <http://www.centrewebdesign.com/>

<https://centrewebdesign.com/about.php>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



------ Original Message ------
From "Art Ginzburg" ***@***.***>
To "sirmspencer/vscode-autohide" ***@***.***>
Cc "ajaxStardust" ***@***.***>; "Author" 
***@***.***>
Date 12/30/2022 2:44:34 AM
Subject Re: [sirmspencer/vscode-autohide] Panel Autohide while 
attempting to select contents (Issue #27)

**Comment by artginzburg** [comment] 2022-12-30 07:52
Ah, okay. That's interesting, because I would like it to not be hidden on click. Do you have any specific configuration for that, or did it just work this way from the start?

**Comment by ajaxStardust** [comment] 2022-12-30 07:54
i'm not trying to receive email about this.

i'll participate in the forum. i'm preoccupied in other things 
presently. thank you.

**Closed as completed** 2023-01-22 21:41 UTC
